# Generated by Django 4.2.7 on 2023-12-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='score',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='documents_achivment',
            name='achivment_year',
        ),
        migrations.RemoveField(
            model_name='documents_dyploma',
            name='dyploma_year',
        ),
        migrations.RemoveField(
            model_name='documents_matura',
            name='exam_year',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='angielski_p',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='angielski_r',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='biologia_p',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='biologia_r',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='chemia_p',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='chemia_r',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='fizyka_p',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='fizyka_r',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='geografia_p',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='geografia_r',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='informatyka_p',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='informatyka_r',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='matematyka_p',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='matematyka_r',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='polski_p',
        ),
        migrations.RemoveField(
            model_name='matura_results',
            name='polski_r',
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='pesel',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
