# Generated by Django 4.2.7 on 2024-01-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_majors_personal_data_matura_results_high_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='apartment_number',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='building_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='postal_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='pesel',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='second_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_data',
            name='sex',
            field=models.CharField(choices=[('Kobieta', 'Kobieta'), ('Mężczyzna', 'Mężczyzna'), ('Inna', 'Inna')], max_length=9, null=True),
        ),
    ]
