# Generated by Django 4.2.7 on 2023-12-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_applications_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_data',
            name='pesel',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
