# Generated by Django 4.2.7 on 2024-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_adress_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents_dyploma',
            name='dyploma_avg',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
