# Generated by Django 4.2.7 on 2023-12-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_matura_results_angielski_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='are_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='decision',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='is_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applications',
            name='is_qualified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='preference',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='tour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documents_achivment',
            name='achivment_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documents_dyploma',
            name='dyploma_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documents_matura',
            name='exam_year',
            field=models.IntegerField(null=True),
        ),
    ]
